name: sqlserver

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "WTuqdzm3qKfJj!m"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver:/var/opt/mssql/data

volumes:
  sqlserver:
    driver: local
