export const ADD_SHOW_CONTACT_MODAL = 'ADD_SHOW_CONTACT_MODAL'
export const EDIT_SHOW_CONTACT_MODAL = 'EDIT_SHOW_CONTACT_MODAL'
export const CLOSE_SHOW_CONTACT_MODAL = 'CLOSE_SHOW_CONTACT_MODAL'

export const LOAD_CONTACTS = 'LOAD_CONTACTS'
export const LOAD_CONTACTS_SUCCESSFULLY = 'LOAD_CONTACTS_SUCCESSFULLY'
export const LOAD_CONTACTS_ERROR = 'LOAD_CONTACTS_ERROR'

export const ADD_CONTACT = 'ADD_CONTACT'
export const ADD_CONTACT_SUCCESSFULLY = 'ADD_CONTACT_SUCCESSFULLY'
export const ADD_CONTACT_ERROR = 'ADD_CONTACT_ERROR'

export const EDIT_CONTACT = 'EDIT_CONTACT'
export const EDIT_CONTACT_SUCCESSFULLY = 'EDIT_CONTACT_SUCCESSFULLY'
export const EDIT_CONTACT_ERROR = 'EDIT_CONTACT_ERROR'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_SUCCESSFULLY = 'DELETE_CONTACT_SUCCESSFULLY'
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR'