export const ADD_SHOW_DEVICE_TYPE_MODAL = 'ADD_SHOW_DEVICE_TYPE_MODAL'
export const EDIT_SHOW_DEVICE_TYPE_MODAL = 'EDIT_SHOW_DEVICE_TYPE_MODAL'
export const CLOSE_SHOW_DEVICE_TYPE_MODAL = 'CLOSE_SHOW_DEVICE_TYPE_MODAL'

export const LOAD_DEVICE_TYPES = 'LOAD_DEVICE_TYPES'
export const LOAD_DEVICES_TYPES_SUCCESSFULLY = 'LOAD_DEVICES_TYPES_SUCCESSFULLY'
export const LOAD_DEVICE_TYPES_ERROR = 'LOAD_DEVICE_TYPES_ERROR'

export const ADD_DEVICE_TYPE = 'ADD_DEVICE_TYPE'
export const ADD_DEVICE_TYPE_SUCCESSFULLY = 'ADD_DEVICE_TYPE_SUCCESSFULLY'
export const ADD_DEVICE_TYPE_ERROR = 'ADD_DEVICE_TYPE_ERROR'

export const EDIT_DEVICE_TYPE = 'EDIT_DEVICE_TYPE'
export const EDIT_DEVICE_TYPE_SUCCESSFULLY = 'EDIT_DEVICE_TYPE_SUCCESSFULLY'
export const EDIT_DEVICE_TYPE_ERROR = 'EDIT_DEVICE_TYPE_ERROR'

export const DELETE_DEVICE_TYPE = 'DELETE_DEVICE_TYPE'
export const DELETE_DEVICE_TYPE_SUCCESSFULLY = 'DELETE_DEVICE_TYPE_SUCCESSFULLY'
export const DELETE_DEVICE_TYPE_ERROR = 'DELETE_DEVICE_TYPE_ERROR'