export const ADD_SHOW_TAX_MODAL = 'ADD_SHOW_TAX_MODAL'
export const EDIT_SHOW_TAX_MODAL = 'EDIT_SHOW_TAX_MODAL'
export const CLOSE_SHOW_TAX_MODAL = 'CLOSE_SHOW_TAX_MODAL'

export const LOAD_TAXES = 'LOAD_TAXES'
export const LOAD_TAXES_SUCCESSFULLY = 'LOAD_TAXES_SUCCESSFULLY'
export const LOAD_TAXES_ERROR = 'LOAD_TAXES_ERROR'

export const ADD_TAX = 'ADD_TAX'
export const ADD_TAX_SUCCESSFULLY = 'ADD_TAX_SUCCESSFULLY'
export const ADD_TAX_ERROR = 'ADD_TAX_ERROR'

export const EDIT_TAX = 'EDIT_TAX'
export const EDIT_TAX_SUCCESSFULLY = 'EDIT_TAX_SUCCESSFULLY'
export const EDIT_TAX_ERROR = 'EDIT_TAX_ERROR'

export const DELETE_TAX = 'DELETE_TAX'
export const DELETE_TAX_SUCCESSFULLY = 'DELETE_TAX_SUCCESSFULLY'
export const DELETE_TAX_ERROR = 'DELETE_TAX_ERROR'