export const ADD_SHOW_WAREHOUSE_MODAL = 'ADD_SHOW_WAREHOUSE_MODAL'
export const EDIT_SHOW_WAREHOUSE_MODAL = 'EDIT_SHOW_WAREHOUSE_MODAL'
export const CLOSE_SHOW_WAREHOUSE_MODAL = 'CLOSE_SHOW_WAREHOUSE_MODAL'

export const LOAD_WAREHOUSES = 'LOAD_WAREHOUSES'
export const LOAD_WAREHOUSES_SUCCESSFULLY = 'LOAD_WAREHOUSES_SUCCESSFULLY'
export const LOAD_WAREHOUSES_ERROR = 'LOAD_WAREHOUSES_ERROR'

export const ADD_WAREHOUSE = 'ADD_WAREHOUSE'
export const ADD_WAREHOUSE_SUCCESSFULLY = 'ADD_WAREHOUSE_SUCCESSFULLY'
export const ADD_WAREHOUSE_ERROR = 'ADD_WAREHOUSE_ERROR'

export const EDIT_WAREHOUSE = 'EDIT_WAREHOUSE'
export const EDIT_WAREHOUSE_SUCCESSFULLY = 'EDIT_WAREHOUSE_SUCCESSFULLY'
export const EDIT_WAREHOUSE_ERROR = 'EDIT_WAREHOUSE_ERROR'

export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE'
export const DELETE_WAREHOUSE_SUCCESSFULLY = 'DELETE_WAREHOUSE_SUCCESSFULLY'
export const DELETE_WAREHOUSE_ERROR = 'DELETE_WAREHOUSE_ERROR'