export const ADD_SHOW_ARTICLE_MODAL = 'ADD_SHOW_ARTICLE_MODAL'
export const EDIT_SHOW_ARTICLE_MODAL = 'EDIT_SHOW_ARTICLE_MODAL'
export const CLOSE_SHOW_ARTICLE_MODAL = 'CLOSE_SHOW_ARTICLE_MODAL'

export const LOAD_ARTICLES = 'LOAD_ARTICLES'
export const LOAD_ARTICLES_SUCCESSFULLY = 'LOAD_ARTICLES_SUCCESSFULLY'
export const LOAD_ARTICLES_ERROR = 'LOAD_ARTICLES_ERROR'

export const ADD_ARTICLE = 'ADD_ARTICLE'
export const ADD_ARTICLE_SUCCESSFULLY = 'ADD_ARTICLE_SUCCESSFULLY'
export const ADD_ARTICLE_ERROR = 'ADD_ARTICLE_ERROR'

export const EDIT_ARTICLE = 'EDIT_ARTICLE'
export const EDIT_ARTICLE_SUCCESSFULLY = 'EDIT_ARTICLE_SUCCESSFULLY'
export const EDIT_ARTICLE_ERROR = 'EDIT_ARTICLE_ERROR'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const DELETE_ARTICLE_SUCCESSFULLY = 'DELETE_ARTICLE_SUCCESSFULLY'
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR'