export const ADD_SHOW_USER_MODAL = 'ADD_SHOW_USER_MODAL'
export const EDIT_SHOW_USER_MODAL = 'EDIT_SHOW_USER_MODAL'
export const CLOSE_SHOW_USER_MODAL = 'CLOSE_SHOW_USER_MODAL'

export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_USERS_SUCCESSFULLY = 'LOAD_USERS_SUCCESSFULLY'
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR'

export const ADD_USER = 'ADD_USER'
export const ADD_USER_SUCCESSFULLY = 'ADD_USER_SUCCESSFULLY'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const EDIT_USER = 'EDIT_USER'
export const EDIT_USER_SUCCESSFULLY = 'EDIT_USER_SUCCESSFULLY'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESSFULLY = 'DELETE_USER_SUCCESSFULLY'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'

export const CHANGE_STATUS_USER_ACCOUNT = 'CHANGE_STATUS_USER_ACCOUNT'