INSERT INTO "InventoryReasons" ("Description", "Type")
VALUES ('AJUSTE POR DIFERENCIA DE INVENTARIO', 'Input'),
       ('COMPRA NACIONAL', 'Input'),
       ('CONSIGNACIÓN RECIBIDA', 'Input'),
       ('DEVOLUCIÓN RECIBIDA', 'Input'),
       ('ENTRADA DE BIENES EN CUSTODIA', 'Input'),
       ('ENTRADA DE BIENES EN PRÉSTAMO', 'Input'),
       ('ENTRADA DE PRODUCCIÓN', 'Input'),
       ('ENTRADA PARA SERVICIO DE PRODUCCIÓN', 'Input'),
       ('ENTRADA POR DEVOLUCIÓN DE PRODUCCIÓN', 'Input'),
       ('ENTRADA POR DEVOLUCIÓN DEL CLIENTE', 'Input'),
       ('ENTRADA POR IDENTIFICACIÓN ERRÓNEA', 'Input'),
       ('INGRESO POR TRANSFERENCIA ALMACENES', 'Input'),
       ('SALDO INICIAL', 'Input');

INSERT INTO "InventoryReasons" ("Description", "Type")
VALUES ('AJUSTE POR DIFERENCIA DE INVENTARIO', 'Output'),
       ('BONIFICACIÓN', 'Output'),
       ('CONSIGNACIÓN ENTREGADA', 'Output'),
       ('DESMEDROS', 'Output'),
       ('DESTRUCCIÓN', 'Output'),
       ('DEVOLUCIÓN ENTREGADA', 'Output'),
       ('DONACIÓN', 'Output'),
       ('EXPORTACIÓN', 'Output'),
       ('GASTOS DE REPRESENTACIÓN', 'Output'),
       ('MERMAS', 'Output'),
       ('MUESTRAS', 'Output'),
       ('PREMIO', 'Output'),
       ('PUBLICIDAD', 'Output'),
       ('RETIRO', 'Output'),
       ('RETIRO PARA ENTREGA A TRABAJADORES', 'Output'),
       ('RETIRO POR CONVENIO COLECTIVO', 'Output'),
       ('RETIRO POR SUSTITUCIÓN DE BIEN SINIESTRADO', 'Output'),
       ('SALIDA A PRODUCCIÓN', 'Output'),
       ('SALIDA DE BIENES EN CUSTODIA', 'Output'),
       ('SALIDA DE BIENES EN PRÉSTAMO', 'Output'),
       ('SALIDA POR DEVOLUCIÓN AL PROVEEDOR', 'Output'),
       ('SALIDA POR IDENTIFICACIÓN ERRÓNEA', 'Output'),
       ('SALIDA POR SERVICIO DE PRODUCCIÓN', 'Output'),
       ('SALIDA POR TRANSFERENCIA ALMACENES', 'Output'),
       ('TRASLADO DE BIENES PARA TRANSFORMACIÓN', 'Output'),
       ('VENTA NACIONAL', 'Output');

INSERT INTO "InventoryReasons" ("Description", "Type")
VALUES ('ENTRADA POR TRANSFERENCIA ENTRE ALMACENES', 'Transfer'),
       ('SALIDA POR TRANSFERENCIA ENTRE ALMACENES', 'Transfer');
