INSERT INTO "TypeOperationSunat" ("Id", "Description")
VALUES ('0101', '0101 - Venta Interna'),
       ('0112', '0112 - Venta Interna - Sustenta Gastos Deducibles Persona Natural'),
       ('0113', '0113 - Venta Interna - NRUS'),
       ('0200', '0200 - Exportación de Bienes'),
       ('0201', '0201 - Exportación de Servicios – Prestación servicios realizados íntegramente en el país'),
       ('0202', '0202 - Exportación de Servicios – Prestación de servicios de hospedaje No Domiciliado'),
       ('0203', '0203 - Exportación de Servicios – Transporte de navieras'),
       ('0204', '0204 - Exportación de Servicios – Servicios a naves y aeronaves de bandera extranjera'),
       ('0205', '0205 - Exportación de Servicios - Servicios que conformen un Paquete Turístico'),
       ('0206', '0206 - Exportación de Servicios – Servicios complementarios al transporte de carga'),
       ('0207',
        '0207 - Exportación de Servicios – Suministro de energía eléctrica a favor de sujetos domiciliados en ZED'),
       ('0208', '0208 - Exportación de Servicios – Prestación servicios realizados parcialmente en el extranjero'),
       ('0301', '0301 - Operaciones con Carta de porte aéreo (emitidas en el ámbito nacional)'),
       ('0302', '0302 - Operaciones de Transporte ferroviario de pasajeros'),
       ('0303', '0303 - Operaciones de Pago de regalía petrolera'),
       ('0401', '0401 - Ventas no domiciliados que no califican como exportación'),
       ('1001', '1001 - Operación Sujeta a Detracción'),
       ('1002', '1002 - Operación Sujeta a Detracción- Recursos Hidrobiológicos'),
       ('1003', '1003 - Operación Sujeta a Detracción- Servicios de Transporte Pasajeros'),
       ('1004', '1004 - Operación Sujeta a Detracción- Servicios de Transporte Carga'),
       ('2001', '2001 - Operación Sujeta a Percepción');
