INSERT INTO public."UndMedida" ("Name", "SunatCode", "SoftDeleted")
VALUES ('BOBINAS', '4A', false),
       ('BALDE', 'BJ', false),
       ('BARRILES', 'BLL', false),
       ('BOLSA', 'BG', false),
       ('BOTELLAS', 'BO', false),
       ('CAJA', 'BX', false),
       ('CARTONES', 'CT', false),
       ('CILINDRO', 'CY', false),
       ('CONOS', 'CJ', false),
       ('DOCENA', 'DZN', false),
       ('FARDO', 'BE', false),
       ('GALÓN INGLES (4,545956L)', 'GLI', false),
       ('GRAMO', 'GRM', false),
       ('HOJA', 'LEF', false),
       ('JUEGO', 'SET', false),
       ('KILOGRAMO', 'KGM', false),
       ('KIT', 'KT', false),
       ('LATAS', 'CA', false),
       ('LIBRAS', 'LBR', false),
       ('LITRO', 'LTR', false),
       ('METRO', 'MTR', false),
       ('MILIGRAMOS', 'MGM', false),
       ('MILILITRO', 'MLT', false),
       ('MILIMETRO', 'MMT', false),
       ('MILLARES', 'MIL', false),
       ('ONZAS', 'ONZ', false),
       ('PALETAS', 'PF', false),
       ('PAQUETE', 'PK', false),
       ('PAR', 'PR', false),
       ('PIEZAS', 'C62', false),
       ('PLACAS', 'PG', false),
       ('PLIEGO', 'ST', false),
       ('PULGADAS', 'INH', false),
       ('TUBOS', 'TU', false),
       ('UNIDAD (BIENES)', 'NIU', false),
       ('UNIDAD (SERVICIOS)', 'ZZ', false),
       ('US GALON (3,7843 L)', 'GLL', false),
       ('YARDA', 'YRD', false),
       ('YARDA CUADRADA', 'YDK', false);
